version: '3.8'

services:
  web:
    image: wyveo/nginx-php-fpm:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=myapp.local
    networks:
      - mynetwork

  db:
    image: mysql:8.0 # Atualize para a versão mais recente do MySQL, por exemplo,  8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
