version: '3.8'

services:
  web:
    image: wyveo/nginx-php-fpm:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=myapp.local
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
